# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: locations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flocations.proto\"`\n\x0fLocationMessage\x12\x11\n\tperson_id\x18\x02 \x01(\t\x12\x11\n\tlongitude\x18\x03 \x01(\t\x12\x10\n\x08latitude\x18\x04 \x01(\t\x12\x15\n\rcreation_time\x18\x05 \x01(\t\"#\n\x0cLocationById\x12\x13\n\x0blocation_id\x18\x01 \x01(\t\"m\n\x10LocationResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tperson_id\x18\x02 \x01(\t\x12\x11\n\tlongitude\x18\x03 \x01(\t\x12\x10\n\x08latitude\x18\x04 \x01(\t\x12\x15\n\rcreation_time\x18\x05 \x01(\t2p\n\x0fLocationService\x12-\n\x07GetById\x12\r.LocationById\x1a\x11.LocationResponse\"\x00\x12.\n\x06\x43reate\x12\x10.LocationMessage\x1a\x10.LocationMessage\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'locations_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCATIONMESSAGE._serialized_start=19
  _LOCATIONMESSAGE._serialized_end=115
  _LOCATIONBYID._serialized_start=117
  _LOCATIONBYID._serialized_end=152
  _LOCATIONRESPONSE._serialized_start=154
  _LOCATIONRESPONSE._serialized_end=263
  _LOCATIONSERVICE._serialized_start=265
  _LOCATIONSERVICE._serialized_end=377
# @@protoc_insertion_point(module_scope)
